import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import background from "../public/img/16150@3x.png"
import backgroundSecond from "../public/img/layer-2@3x.png"
import logo from "../public/img/pakan-logo-types-01@3x.png"
import hamMenu from "../public/img/menu-ham-b@3x.png"
import Call from "../public/img/call-center-g@3x.png"
import Time from "../public/img/time-g@3x.png"
import Pin from "../public/img/location.png"
import MyLoc from "../public/img/gps.png"
import MainBackground from "../public/img/mask-group-1@3x.png"
import Tracking from "../public/img/tracking@3x.png"
import backgroundVideo from "../public/img/layer-1@3x.png"
import backgroundPlay from "../public/img/screenshot-30@3x.png"
import Sewing from "../public/img/sewing-b@3x.png"
import Urgent from "../public/img/urgent-g@3x.png"
import Press from "../public/img/press-g@3x.png"
import Colouring from "../public/img/colouring-g@3x.png"
import Spoting from "../public/img/spotting-g@3x.png"
import More from "../public/img/more@3x.png"
import WorkerLaundry from "../public/img/worker-laundry-ironed-clothes-iron-dry-542303516-5-abf-0-cbcba-617700372-b-3-b-75@3x.png"





const YekanBakh = localFont({
  src: "./fonts/YekanBakh-Regular.ttf",
  variable: "--font-yekanBakh",
  weight: "100 900",
});
const YekanBakhMono = localFont({
  src: "./fonts/YekanBakh-Bold.woff",
  variable: "--font-YekanBakh-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div dir="rtl"
        className={`${styles.page} ${YekanBakh.variable} ${YekanBakhMono.variable}`}
      >
        <header className={styles.header}>
          <div className={styles.headerNav}>
            <div dir="ltr" className={styles.headerInfo}>

            <span className={styles.callNumber}>
            <Image
              className={styles.call}
              src={Call}
              alt="Call"
              width={20}
              height={20}
              priority
            /> 
            021-41774
            <div className={styles.lineFirst}></div>
            </span>
            <span>
            <Image
              className={styles.Time}
              src={Time}
              alt="Time"
              width={20}
              height={20}
              priority
            />
              روز های کاری 8:00 تا 18:30 | جمعه ها 9:00 تا 17:00
               
            </span>
            <div className={styles.lineFirst}></div>
          </div>
          <div className={styles.line}></div>
          <div className={styles.Navbar}>
           <span className={styles.NavbarFirst}>
              <Image
                className={styles.logo}
                src={logo}
                alt="logo"
                width={55}
                height={55}
                priority
              />
              <Image
                className={styles.hamMenu}
                src={hamMenu}
                alt="hamMenu"
                width={22}
                height={22}
                priority
              />

              <i>درباره ما</i>
              <i>خدمات</i> 
              <i>خدمات سازمانی</i> 
              <i>نحوه درخواست</i> 
              <i>تماس با ما</i> 
              <i> ویترین</i>
              <i> بلاگ</i>  
            </span>
            <span className={styles.NavbarSecond}> 
              <a href="#">ثبت نام</a> 
              <button>ورود</button> 
            </span> 
          </div>   
        
          </div>
         
          
          <div className={styles.headerfirst}>
            <Image
              className={styles.headerBack}
              src={background}
              alt="background"
              priority
            /> 
             <span className={styles.title}>خونه تکونی همراه شماییم</span>
             <span className={styles.description}>باز و نصب و شستن پرده‌ها باما</span>
             <div className={styles.headerLocation}>
              <div className={styles.headerLoc}>
                <div className={styles.headerLocFirst}>
                  <Image className={styles.pin}
                  src={Pin}
                  alt="Pin"
                  width={24}
                  height={30}
                  priority
                  /> 
                  <div className={styles.address}>
                    <p className={styles.addressText}>محله سعادت آباد - ویرایش</p>
                    <span className={styles.addressLine}></span>
                  </div>
                
                
                  <div className={styles.MyLoction}>
                      <Image className={styles.MyLoc}
                        src={MyLoc}
                        alt="MyLoc"
                        priority
                    
                      /> 
                  </div>
                </div>
              <button className={styles.findLoc} >بررسی محدوده و درخواست سرویس</button>
            
            </div></div>
             
          </div>
          
          <div className={styles.headerWhy}>
              <Image className={styles.headerWhyBack}
                src={MainBackground}
                alt="MainBackground"
                priority
              /> 
              <div className={styles.headerWhyTitle}>
                <h2>چرا پاکان ؟</h2>
                <h3>ویژگی های پاکان</h3>

              </div>
              <div className={styles.headerWhyDesc}>
                <div className={styles.headerWhyDescTitle}>
                <span className={styles.TrackingFirst}> 
                <Image
                  className={styles.Tracking}
                  src={Tracking}
                  alt="Tracking"
                  width={40}
                  height={30}
                  priority
                />                
                <p>ویژگی متمایز شماره یک پاکان</p>
                </span>  
                <span className={styles.TrackingSecond}
                > 
                <Image
                  className={styles.Tracking}
                  src={Tracking}
                  alt="Tracking"
                  width={40}
                  height={30}
                  priority
                />                
                <p>ویژگی متمایز شماره یک پاکان</p>
                </span>                 
                <span>
                <Image
                  className={styles.Tracking}
                  src={Tracking}
                  alt="Tracking"
                  width={40}
                  height={30}
                  priority
                />                 
                <p>ویژگی متمایز شماره یک پاکان</p>
                </span> 
                <span> 
                <Image
                  className={styles.Tracking}
                  src={Tracking}
                  alt="Tracking"
                  width={40}
                  height={30}
                  priority
                />                 
                <p>ویژگی متمایز شماره یک پاکان</p>
                </span>  
                </div>                
                <div className={styles.headerWhyDescLine}>
                <div className={styles.headerWhyDescLight}></div>
                </div>
                <div className={styles.headerWhyDescDetail}>
                  <h3>ویژگی متمایز شماره یک پاکان</h3>
                  <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراح
                    ان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد
                   نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته <br></br>
                    لورم ایپسوم متن ساختگی با تولید سادگی نام
                    فهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگر
                    ها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                </div>

              </div>
          </div>
        </header>
        <main className={styles.main}>
        
          <div className={styles.mainVideo}>
              <h3 className={styles.titleVideo}>کارگاه پاکان</h3>
              <p className={styles.descVideo}>بهره‌گیری از پیشرفته‌­ترین تکنولوژی و ماشین‌آلات روز دنیا، نسل جدید خشکشویی هوشمند</p>
              <div className={styles.videoBack}>
                <Image
                className={styles.backgroundVideo}
                src={backgroundVideo}
                alt="backgroundVideo"
                priority
              /> 
              <Image
                className={styles.backgroundSecond}
                src={backgroundSecond}
                alt="backgroundSecond"
                priority
              /> </div>
              <div className={styles.playerVideo}>
              <Image
                className={styles.backgroundPlay}
                src={backgroundPlay}
                alt="backgroundPlay"
                priority
              /> 
              </div> 
          </div>
          <div className={styles.mainDescription}>
            <h3 className={styles.titleDescription}>سرویس مورد نظر خود را انتخاب کنید</h3>
            <p className={styles.descDescription}>سرویس های پاکان</p> 
            <div className={styles.detailDescription}>
              <div className={styles.serviceTitle}>
                <span>
                  <Image
                    className={styles.Sewing}
                    src={Sewing}
                    alt="Sewing"
                    width={50}
                    height={58}
                    priority
                  />           
                  <p>نام سرویس مثال</p>
                </span>
                <span>
                  <Image
                    className={styles.Urgent}
                    src={Urgent}
                    alt="Urgent"
                    width={77}
                    height={50}
                    priority
                  />           
                  <p>نام سرویس مثال</p>
                </span>
                <span>
                  <Image
                    className={styles.Press}
                    src={Press}
                    alt="Press"
                    width={66}
                    height={50}
                    priority
                  />           
                  <p>نام سرویس مثال</p>
                </span>
                <span>
                  <Image
                    className={styles.Colouring}
                    src={Colouring}
                    alt="Colouring"
                    width={51}
                    height={51}
                    priority
                  />           
                  <p>نام سرویس مثال</p>
                </span>
                <span>
                  <Image
                    className={styles.Spoting}
                    src={Spoting}
                    alt="Spoting"
                    width={51}
                    height={51}
                    priority
                  />           
                  <p>نام سرویس مثال</p>
                </span>
                <span>
                <Image
                    className={styles.More}
                    src={More}
                    alt="More"
                    width={51}
                    height={51}
                    priority
                  />         
                  <p>نام سرویس مثال</p>
                </span>
              </div>
              <div className={styles.serviceDescription}>
                <span 
                className={styles.WorkerLaundry}>
                  <Image
                      className={styles.WorkerLaundryPic}
                      src={WorkerLaundry}
                      alt="WorkerLaundry"
                      priority
                     
                    /> 
                </span>
                
                  <span  className={styles.WorkerLaundryDesc}>
                    
                  <h3 >نام سرویس مثال</h3>
                  <p >
                    لورم ایپسوم متن ساختگی با تولید سادگی نام
                    فهوم از صنعت چاپ و با استفاده از طراحان گرا
                    فیک است. چاپگرها و متون بلکه روزنامه و مجله
                     در ستون و سطرآنچنان که لازم است و برای شرای
                    ط فعلی تکنولوژی مورد نیاز و کاربردهای متنو
                    ع با هدف بهبود ابزارهای کاربردی می باشد
                    . کتابهای زیادی در شصت و سه درصد گذشته،
                    </p> 
                  </span> 
              </div>
            </div>
          </div>
          
            
      
         
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
